Profile page
alisondraV/foodizzy pull request #61
Opened 2021-03-09 14:49 UTC by alisondraV

2021-03-17 19:06 UTC, ANDREYDEN requested changes
Awesome work!
1. When a user switches families (accepts the invite), there's a type error being thrown in the console. This might be fixed by using `CurrentFamily.listenForChanges` and forwarding the user back to the family page.
2. When updating the profile with a user without a family it fails with a family reference error.

2021-03-18 13:36 UTC, alisondraV commented on src/views/profile-settings/Invitations.vue
> +      // TODO: update user's family
It was related to reloading the family. I added your favourite `CurrentFamily.instance.listenForChanges();` method. Seems to work😅

2021-03-18 13:40 UTC, alisondraV commented on src/views/profile-settings/QuitFamily.vue
> +    window.location.reload();
Opened up a new issue for this: #80

2021-03-18 13:51 UTC, alisondraV commented on src/views/profile-settings/Invitations.vue
> +      await this.showAlert("You've accepted the invitation");
Opened up a new issue for this: #81

2021-03-18 16:48 UTC, ANDREYDEN requested changes
All good except that one thing.

2021-03-18 16:48 UTC, ANDREYDEN commented on src/views/profile-settings/Family.vue
> +      this.familyMembers = await Firestore.instance.getUsersByEmail(this.members);
`this.members` will be empty on start.
```suggestion
      this.familyMembers = await Firestore.instance.getUsersByEmail(this.family.members);
```

2021-03-18 16:59 UTC, ANDREYDEN approved these changes
Ship it!

2021-03-18 17:02 UTC, merged